# Generated by Django 5.0.6 on 2024-05-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myweb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="full_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
